version: '2'

services:
  mysql-dev:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=freelance
      - MYSQL_ROOT_HOST=192.168.0.48/255.255.255.248
    ports:
      - 3308:3306
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
