version: "3"

services:
  mysql-dev:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ecEEn7h3mC8OCR
      MYSQL_DATABASE: freelance
      MYSQL_USER: user
      MYSQL_PASSWORD: ecEEn7h3mC8OCR
    ports:
      - 3308:3306
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
